#!/usr/bin/env bash

USAGE="Usage: `basename $0` input"

if [ $# != 1 ]; then
    echo $USAGE >&2
    exit 1
fi

file=$(realpath $1)

docker run \
  --rm \
  -v ${file}:/in \
  -u $(id -u):$(id -g) \
  --entrypoint ffprobe \
  deluan/navidrome:latest \
    -show_format \
    -print_format json \
    /in