#!/usr/bin/env sh

set -o errexit

log() {
    if [ "${SONOSIFY_LOG}" == "true" ]; then
        echo $1 1>&2
    fi
}

USAGE="Usage: `basename $0` input output"

if [ $# -ne 2 ]; then
    echo $USAGE >&2
    exit 1
fi

I=$1
O=$2

[ ! -e "${I}" ] && \
    echo "Input file ${I} does not exist" >&2 && \
    exit 1

stream0=$(ffprobe -select_streams 0 -show_streams "${I}" 2>/dev/null)

codec_type=$(echo "${stream0}" | grep "^codec_type=" | cut -d = -f 2)
if [ "${codec_type}" != "audio" ]; then
    echo "Expected stream 0 to be audio, but is ${codec_type}" >&2
    exit 1
fi

codec_name=$(echo "${stream0}" | grep "^codec_name=" | cut -d = -f 2)
sample_fmt=$(echo "${stream0}" | grep "^sample_fmt=" | cut -d = -f 2)
sample_rate=$(echo "${stream0}" | grep "^sample_rate=" | cut -d = -f 2)

case "${codec_name}" in
    mp3)
        log "sonosify: mp3@${sample_fmt}:${sample_rate} -> mp3@${sample_fmt}:${sample_rate}"
        ffmpeg \
            -i "${I}" \
            -map 0:a \
            -c:a copy \
            -map_metadata -1 \
            -f mp3 \
            "${O}" 2>/dev/null
    ;;
    flac)
        out_sample_fmt="${sample_fmt}"

        # flac sample rates -> https://tools.ietf.org/id/draft-xiph-cellar-flac-00.html#rfc.section.10.19.4
        case "${sample_rate}" in
            88200)  out_sample_rate="44100";;
            96000)  out_sample_rate="48000";;
            176400) out_sample_rate="44100";;
            192000) out_sample_rate="48000";;
            *)      out_sample_rate="${sample_rate}";;
        esac

        log "sonosify: flac@${sample_fmt}:${sample_rate} -> flac@${out_sample_fmt}:${out_sample_rate}"

        ffmpeg \
            -i "${I}" \
            -af "aresample=resampler=soxr:out_sample_fmt=${out_sample_fmt}:out_sample_rate=${out_sample_rate}" \
            -map_metadata -1 \
            -f flac \
            "${O}" 2>/dev/null
    ;;
    alac)
        out_sample_fmt="${sample_fmt}"

        case "${sample_rate}" in
            88200)  out_sample_rate="44100";;
            96000)  out_sample_rate="48000";;
            *)      out_sample_rate="${sample_rate}";;
        esac

        log "sonosify: alac@${sample_fmt}:${sample_rate} -> flac@${out_sample_fmt}:${out_sample_rate}"

        ffmpeg \
            -i "${I}" \
            -af "aresample=resampler=soxr:out_sample_fmt=${out_sample_fmt}:out_sample_rate=${out_sample_rate}" \
            -map_metadata -1 \
            -f flac \
            "${O}" 2>/dev/null
    ;;
    *)
        echo "File ${I} has an unsupported codec ${codec_name}" >&2
        exit 1
    ;;
esac
